# THIS GOES IN AUTOMATIONS.YAML
# PEOPLE_HOME SENSOR JUST MEANS IT DOESNT TUN ON IF NO ONE IS THERE TO SEE IT, ADJUST AS NEEDED FOR YOUR SETUP

- alias: Thundercloud Sunny
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'clear-day'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 255
        rgb_color: [255,226,145]
        effect: solid

- alias: Thundercloud Sunny Night
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'clear-night'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 150
        rgb_color: [255,181,108]
        effect: solid

- alias: Thundercloud Cloudy
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'cloudy'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 255
        rgb_color: [71,71,255]
        effect: solid

- alias: Thundercloud Fog
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'fog'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 255
        rgb_color: [90,255,36]
        effect: solid

- alias: Thundercloud Partly Cloudy
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'partly-cloudy-day'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 255
        rgb_color: [71,208,255]
        effect: solid

- alias: Thundercloud Partly Cloudy Night
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'partly-cloudy-night'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 110
        rgb_color: [71,208,255]
        effect: solid

- alias: Thundercloud Rain
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'rain'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 120
        rgb_color: [36,36,255]
        effect: juggle

- alias: Thundercloud Snow
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'snow'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 120
        rgb_color: [0,255,255]
        effect: juggle

- alias: Thundercloud Sleet
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'sleet'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 150
        rgb_color: [0,255,190]
        effect: glitter

- alias: Thundercloud Wind
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'wind'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 200
        rgb_color: [255,226,145]
        effect: juggle

- alias: Thundercloud Thunderstorm
  trigger:
    platform: time_pattern
    minutes: "/5"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.dark_sky_icon_0h
        state: 'thunderstorm'
      - condition: state
        entity_id: binary_sensor.people_home
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.thundercloud
      data:
        brightness: 180
        rgb_color: [255,255,255]
        effect: lightning
